### PR TITLE
add sqlite wasi os polyfill

### PR DESCRIPTION
**Pull request by dasimmet**
copied from https://github.com/ericsink/wasm2cil/tree/master/sqlite3

### CODE REVIEW

**Comment by vrischmann** [comment]
I'd like to see an explanation as to why this is useful, what the polyfill does, etc. I have no experience with wasm/wasi so I have no idea how to approach this. How do I test this ?

**Comment by Cloudef** [comment]
That wasi polyfill looks quite incomplete. You can use it externally anyways by compiling the VFS and calling `sqlite3_vfs_register(sqlite3_demovfs(), 0);` in your app before using zig-sqlite.

**Comment by vrischmann** [comment]
Hey @dasimmet, do you intend to work on this PR again ?

**Comment by vrischmann** [comment]
Closing for now. If needed we'll reopen it.

**Pull request closed without merging**
