### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by nektro**
Ran into some small bugs while getting started. This PR contains fixes for those issues.

### CODE REVIEW

**Comment by nektro** [comment]
Ah it seems the `init` change broke some of the tests. Lemme know if i should revert that one or fix the issues

**Comment by vrischmann** [comment]
I don't really remember why I wrote `init` that way, I'm ok with this change if you can fix the tests.

**Comment by vrischmann** [comment]
I just reread the changes, I don't think `QueryOptions` not having an allocator field is a bug: if you need an allocator then you should call `nextAlloc` on the iterator, which takes an explicit allocator argument. The interface of `next` is explicitly made so that's there no allocator anywhere.
`readStruct` and `readField` do expect an allocator on the `options` argument but this is fine since they take `anytype` and the type provided by `nextAlloc` will have the `allocator` field.

Am I missing something ?

**Comment by nektro** [comment]
Ah, no that's fair. My misunderstanding.

**Comment by vrischmann** [comment]
> Ah, no that's fair. My misunderstanding.

:+1: I'll try to improve the documentation for this

**Comment by vrischmann** [comment]
Thanks !

**Pull request merged**
