### PR TITLE
fix: keep up with zig master

### LINKED ISSUE #151: Does not work on latest Zig
Build system can not import it as dependency using latest Zig. There was a build system overhaul a few days ago.

### PR DESCRIPTION
**Pull request by jiacai2050**
Close #151

### CODE REVIEW

**Review by vrischmann — APPROVED** [review]
Thanks !

**Comment by vrischmann** [comment]
I just noticed it's a draft, are you going to work more on this PR or can I merge as is ?

**Comment by jiacai2050** [comment]
Not now, this PR needs further polish.

**Comment by jiacai2050** [comment]
@vrischmann PTAL

**Review by vrischmann — APPROVED** [review]

**Comment by vrischmann** [comment]
Thanks!

**Pull request merged**
