### PR TITLE
Update SQLite's sources to 3.35 version

### PR DESCRIPTION
**Pull request by data-man**
The wonderful library, thank you!

Proposal: move SQLite's sources to `c` folder (or `csources`, etc.)
In the future, this folder can contain very useful SQLite's extensions.

### CODE REVIEW

**Comment by vrischmann** [comment]
Thanks for the PR  !

I'm fine with moving the C files in a subdirectory. I have never used SQLite extensions so I'm not sure what would be required to make them work with the bundled source code.

**Comment by data-man** [comment]
> I'm fine with moving the C files in a subdirectory. 

Ok. What name is preferred?
`c`
`csources`
`sqlite-c`

> I have never used SQLite extensions

Oh, I recommend trying them! :)

**Comment by vrischmann** [comment]
`c` is fine.

I've read about some official extensions but haven't had any use case requiring them, yet :)

**Comment by data-man** [comment]
> c is fine.

Done.

**Pull request merged**
